### ISSUE TITLE
Migration to Github (except translations)

### ISSUE THREAD

**Issue by three-comrades** [mnemosyne-proj/mnemosyne#1]
Relevant ML threads: [recent](https://groups.google.com/forum/#!topic/mnemosyne-proj-devel/WvRLdiOQ4Oc), [last year](https://groups.google.com/forum/#!topic/mnemosyne-proj-devel/n6JHPgRdWIw)
Before migration:
- [x] Test integration with launchpad's translation service
  - Problem: qastaging.launchpad.net and staging.launchpad.net don't import the branch properly. Which is not surprising, because they don't really work to begin with. But the import works fine [here](https://code.launchpad.net/~jmehne/mnemosyne-proj/trunk), so I don't think it will be a problem. Marking as solved.
- [x] Run tests on Windows automatically with Appveyor
  - [x] Initial setup
  - [x] Fix for latex on windows: install miktex.portable with chocolatey and cache it
  - [x] Fix test hang. (Reason: running `dvipng` resulted in the miktex installer being triggered, because `zhmetrics` wasn't installed.)
  - [x] Optional: find out how to install `zhmetrics` from local file. Can be done, but package is only 35kB bit, so not worth it.
  - [x] Find out reason for excessive test failures
- [x] Create a top-level README.md file
- [x] Prepare website udpate, but don't update the website yet (see website_update.md):
  - [x] Bug reporting on Github
  - [x] Hacking: Github + git workflow
  - [x] Translation on launchpad
 
Steps immediately before conversion:
- [x] Create Pull Request on launchpad for changes that I've accumulated in the `github` branch here on Github
  - [x] Wait until the (revised) pull request is merged
- [x] Ask Peter to merge his experimental branch into Launchpad master
- [x] Optional, but nice: Make tests work

Actual conversion:
- [x] Convert bzr -> git using the steps outlined in my email (don't forget to remove the additional file mentioned by Peter)
- [x] Push the converted, new 'productive' repository to Github
- [x] Update the launchpad page:
  - [x] Close bug tracker
  - [x] Migrate open bug reports
  - [x] Switch translation service to git -> bzr import from Github 
  - [ ] Optional: create a git mirror on Launchpad
  - [x] Update description: only used for translation, please report bugs and get the code on Github (link)
- [x] Update website with the pre-prepared changes.
- [x] Update project description here on Github to reflect that it is the main repository.

**Comment by pbienst** [comment]
Almost there, main thing left is the translation infrastructure.

**Comment by three-comrades** [comment]
Okay, first things first, I created a copy of the trunk branch on launchpad as a backup.

Now, we need to replace the current trunk branch on launchpad with a new one that is imported from Github into a bzr branch on launchpad. The import process will take some time, but once it is done the translations infrastructure should pick up the branch just fine.

You can either give me admin rights an launchpad (jmehne), or do it yourself. If you are on the code page on launchpad there should be a 'configure code' button (that's at least what I see in the staging area). Then, choose bzr, `import code frome somwhere else`, `branch name` is `master`, the url is `https://github.com/mnemosyne-proj/mnemosyne.git`, `branch owner` should be `mnemosyne-project`.

**Comment by pbienst** [comment]
I assume it's importing now...

**Comment by three-comrades** [comment]
Urgh, launchpad chokes on the `gpgsig` field of the most recent merge commit. Seems to be [this](https://bugs.launchpad.net/ubuntu/+source/bzr-git/+bug/1084403) unsolved bug. I guess Github automatically adds that if you have a gpg key imported into your account ...

**Comment by three-comrades** [comment]
Hm, let me remove the `gpgsig` field in that commit and force-push to the repository. Let's see if that fixes the import and if the translations then work correctly.

Then, we need to check how to make Github not write the `gpgsig` field.

**Comment by pbienst** [comment]
BTW, I also added you to the mnemosyne-proj devel group on Launchpad, so that you have admin access.

**Comment by three-comrades** [comment]
Thanks!

Okay, the import into launchpad as a bzr repository was successful.

It seems to me that the translations infrastructure is automatically tracking the correct branch, but I'm not a 100% sure if it works. Can you try and create a change that should be picked up so we can test it? I don't quite understand the workflow to do that.

**Comment by pbienst** [comment]
Made a trivial commit. Tomorrow, the following string should appear on Launchpad, which we can try to translate: "TRANSLATION TEST"

**Comment by three-comrades** [comment]
It works already! The file is being marked as imported in the translation infrastructure and I could [translate the string](https://translations.launchpad.net/mnemosyne-proj/2.x/+pots/mnemosyne/de/+filter?person=jmehne).

**Comment by pbienst** [comment]
Cool! I guess this completes the switch and we can close this issue then.

**Comment by three-comrades** [comment]
Perfect! Sometime this week, I will look into the windows test failure on Python 3.5.
