### ISSUE TITLE
Tracking issue for submitting Mnemosyne on F-Droid

### ISSUE THREAD

**Issue by marmistrz** [mnemosyne-proj/mnemosyne#83]
As mnemosyne currently doesn't have any proprietary dependencies anymore, I'd like to bring it into F-Droid. This issue will be tracking the progress. 

Current progress:
* [x] `make android` works
* [ ] building the JNI works
* [ ] building the app works

The issues will be discussed in the follow-up posts.

**Comment by marmistrz** [comment]
What are exactly the CrystaX NDK features that Mnemosyne depends upon and are not present in the upstream NDK?

**Comment by pbienst** [comment]
A prebuilt Python interpreter :-)

**Comment by pbienst** [comment]
In the latest development release, Crystax is no longer used. However, we do use the Python libraries from the python-for-android project.
Still, I'm closing this issue for the moment due to lack of progress, but feel free to reopen this if you want to start working on this again.
